In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score

Importing the Dependencies

28

Data Collection and Analysis

PIMA Diabetes Dataset

In [ ]:
# loading the diabetes dataset to a pandas DataFrame
data = pd.read_csv('diabetes.csv')

In [ ]:
pd.read_csv?

<_io.TextIOWrapper name='file.txt' mode='w' encoding='UTF-8'>

In [ ]:
# printing the first 5 rows of the dataset
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [ ]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
data.value_counts().sum()

768

In [ ]:
data["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

0 --> Non-Diabetic

1 --> Diabetic

In [ ]:
data["Outcome"].value_counts(normalize=True)*100

Outcome
0    65.104167
1    34.895833
Name: proportion, dtype: float64

In [ ]:
data.groupby("Outcome").mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [ ]:
# separating the data and labels
x=data.drop("Outcome",axis=1)
y=data["Outcome"]

In [ ]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [ ]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

Data Standardization

In [ ]:
scaler=StandardScaler()

In [ ]:
scaler_data=scaler.fit_transform(x)

In [ ]:
x=scaler_data

In [ ]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

Train Test Split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
x_train

array([[-0.84488505,  0.09719231,  0.25303625, ..., -0.53211885,
        -1.12311057, -0.27575966],
       [-0.84488505, -0.81042491,  0.66661825, ...,  0.38169971,
        -0.72143478,  0.83038113],
       [-1.14185152, -0.84172205,  0.04624525, ...,  1.4605133 ,
        -0.37714125, -1.04154944],
       ...,
       [ 0.04601433,  0.12848945,  0.04624525, ..., -0.39250768,
         2.02989333,  1.00055664],
       [-0.25095213, -0.15318486,  0.25303625, ..., -0.72249772,
        -1.10196973, -0.78628618],
       [ 0.04601433, -0.34096773, -0.16054575, ..., -0.01174995,
        -0.00264654, -0.36084741]])

In [ ]:
x_test

array([[-0.54791859, -1.02950492,  0.25303625, ..., -0.37981576,
        -0.73351526, -0.95646168],
       [-0.54791859,  0.25367803,  0.77001375, ..., -0.506735  ,
        -0.56740873, -0.53102292],
       [-1.14185152, -0.59134489,  0.45982725, ...,  0.31824009,
        -0.70633419, -0.78628618],
       ...,
       [-1.14185152,  0.34756947,  0.45982725, ...,  0.05170968,
        -0.23821579, -1.04154944],
       [ 0.3429808 ,  0.5040552 ,  2.01075975, ...,  2.1331853 ,
        -0.73955549,  0.31985461],
       [-0.84488505, -1.4989621 , -0.98770975, ..., -1.14133123,
        -0.676133  , -1.04154944]])

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(768, 8) (614, 8) (154, 8)


Training the Model

In [ ]:
classifier = svm.SVC(kernel='linear')

In [ ]:
classifier=svm.SVC(kernel="linear")

In [ ]:
classifier.fit(x_train,y_train)

SVC(kernel='linear')

In [ ]:
classifier.coef_

array([[ 0.39941591,  1.0014548 , -0.16258498, -0.02775598, -0.09371428,
         0.5257599 ,  0.2435654 , -0.03971892]])

In [ ]:
os.listdir()

['test',
 'file.txt',
 '.ipynb_checkpoints',
 '1',
 'sample-code.ipynb',
 '.git',
 'File_handling_reading_and_writing.ipynb',
 'README.md']

Model Evaluation

Accuracy Score

In [ ]:
y_train_prediction=classifier.predict(x_train)

In [ ]:
training_accuracy=accuracy_score(y_train_prediction,y_train)

In [ ]:
print("Accuracy score of training data :",training_accuracy)

Accuracy score of training data : 0.7719869706840391


In [ ]:
y_test_prediction=classifier.predict(x_test)

In [ ]:
test_accuracy=accuracy_score(y_test_prediction,y_test)

In [ ]:
test_accuracy

0.7662337662337663

In [ ]:
#Making prediction System through function

'/home/jovyan/work/file_test.txt'

In [ ]:
input_data=(10,166,72,19,175,25.8,0.587,51)

In [ ]:
input_data

(10, 166, 72, 19, 175, 25.8, 0.587, 51)

In [ ]:
input_data_as_numppy=np.asarray(input_data)

In [ ]:
input_reshape=input_data_as_numppy.reshape(1,-1)

In [ ]:
std_data=scaler.transform(input_reshape)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
std_data

array([[ 1.82781311,  1.41167241,  0.14964075, -0.09637905,  0.82661621,
        -0.78595734,  0.34768723,  1.51108316]])

In [ ]:
prediction=classifier.predict(std_data)

In [ ]:
prediction[0]

1

In [ ]:
if prediction[0]:
  print("The person is diabetic")
else:
  print("The person is not diabetic")

The person is diabetic


In [ ]:
import pickle
pickle.dump(classifier,open("model.pkl","wb"))

Store our model using pickle

In [ ]:
import pickle
pickle.dump(classifier,open("model.pkl","wb"))

Load pickle model

In [ ]:
model=pickle.load(open("model.pkl","rb"))

In [ ]:
model.coef_

array([[ 0.39941591,  1.0014548 , -0.16258498, -0.02775598, -0.09371428,
         0.5257599 ,  0.2435654 , -0.03971892]])

A function transform into array and standard values

In [ ]:
def Prediction(inp):
  input_array=np.asarray(inp)
  input_reshape=input_array.reshape(1,-1)
  std_data=scaler.transform(input_reshape)
  prediction=model.predict(std_data)

  return prediction[0]

Input values

In [ ]:
input_data=[1,85,66,29,0,26.6,0.351,31]

Final values


In [ ]:
out_put=Prediction(input_data)
if out_put:
  print("The person is Diabetic")
else:
  print("The person is not Diabetic")

The person is not Diabetic


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
